---
dist: bionic

language: python

python:
  - "3.5"

addons:
  apt:
    packages:
      - build-essential
      - devscripts
      - equivs
      - fakeroot
      - gir1.2-gtk-3.0
      - help2man
      - python3-gi
      - python3-numpy
      - python3-opengl
      - python3-pytest
      - python3-setuptools
      - python3-svg.path
      - python3-yaml

script:
  # The commands below are run within the virtualenv with python 3.5. Thus python packages from
  # the system are ignored for "make test".
  - pip install flake8 pytest
  - make test
  - ./setup.py sdist
  - pycam/run_gui.py --help
  - pycam/run_gui.py --version
  - pycam/run_cli.py --help
  - pycam/run_cli.py --version
  - debian/rules prep-source
  - dpkg-buildpackage -us -uc
